filter:
    excluded_paths:
        - tests/
        - vendor/
before_commands:
    - composer install
tools:
    php_code_sniffer:
        config:
            standard: PSR2
        extensions:
            - php
        enabled: true
        filter:
            paths: ["*.php"]
    php_cpd:
        min_lines: 5
        min_tokens: 70
        names:
            - '*.php'
        excluded_dirs:
            - tests/
            - vendor/
        enabled: false
    php_mess_detector:
        enabled: true
    php_pdepend:
        enabled: true
    php_sim:
        enabled: true
        filter:
            excluded_paths:
                - tests/
                - vendor/
    php_analyzer:
        enabled: true
        filter:
            excluded_paths:
                - tests/
                - vendor/
    sensiolabs_security_checker:
        enabled: true
    php_changetracking:
        enabled: true
