language: php
php:
  - 7.0
  - 5.6
  - 5.5
matrix:
  allow_failures:
    - php: 7.0 # This should be fixed, temporary for the PHP7 support badge
install:
  - composer self-update
  - composer install
script:
  - vendor/bin/robo test
