language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
install:
  - composer self-update
  - composer install --dev
script:
  - vendor/bin/robo test:coverage-codeclimate
addons:
  code_climate:
    repo_token: 3798532b8ba006dda3541198ac9e2b9b21825dc476540ee1d9397b0665f8d033
after_success:
  - vendor/bin/test-reporter